modLoader = "javafml" #mandatory
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile = "assets/bosswhackers/textures/item/wither_whacker.png"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''
#[[dependencies.${mod_id}]]
#modId = "minecraft"
#mandatory = true
#versionRange = "1.20.3"
#ordering = "NONE"
#side = "BOTH"
