# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.4.0
group=net.boypika
java_version=21

# Common
minecraft_version=1.21
mod_name=Boss Whackers
mod_author=BoyPika
mod_id=bosswhackers
license=GPL-3.0
credits=
description=Adds weapons to one-shot the Wither, Ender Dragon, and the Warden
minecraft_version_range=[1.21, 1.21.1]

# Fabric
fabric_version=0.102.0+1.21
fabric_loader_version=0.17.2

# NeoForge
neoforge_version=21.0.143
neoforge_loader_version_range=[1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false